title: Azure Minds - Blog on Data Engineering, Machine Learning and Natural Language Processing
description: Writing about all things machine learning and data engineering.
url: "https://yourusername.github.io/blog" # the subpath of your site, e.g. /blog
baseurl: "" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: "Patrick Stewart"
  email: patrickstewart1@hotmail.com
exclude:
  - readme.md
# Build settings
plugins:
  - jekyll-feed

